### PR TITLE
Reformat badge

### PR DESCRIPTION
**Pull request by maelle**
:wave: @rorynolan!

Your repo status badge was formatted weirdly.

For info I was using the repo as a test for https://github.com/ropensci/codemetar/issues/169 We're thinking to enforce repostatus.org badges but your README made me realize we won't ask authors to replace lifecycle badges with them, one can have two.

You might also be interested in this discussion, I meant to tag you https://github.com/ropensci/onboarding-meta/issues/56

### CODE REVIEW

**Comment by rorynolan** [comment]
Hi @maelle 
Thanks for the PR. I agree that the current layout of badges isn't ideal. I had a look at the discussion in https://github.com/ropensci/onboarding-meta/issues/56. There doesn't seem to be a conclusion on what should be done but if there ever is, I'm happy to implement it.
Rory

**Comment by maelle** [comment]
Thank you! I'd also be happy for you to chime in in that thread with your opinion on what a table should look like!

**Comment by rorynolan** [comment]
Alrighty I did it!

**Comment by maelle** [comment]
Thank you!

**Pull request merged**
